### ISSUE TITLE
Disconnected root commit fails builds of PR branches 

### ISSUE THREAD

**Issue by HEskandari** [Particular/NServiceBus.CommonLogging#11]
As per the comment [here](https://github.com/Particular/PlatformDevelopment/issues/1576#issuecomment-349573836), we need to experiment with ignored commits or if that doesn't work, try history rewriting.

![image](https://user-images.githubusercontent.com/132117/33694038-0e58a044-db4a-11e7-8116-3a30c06cbd7c.png)

**Comment by bording** [comment]
I've completely rewritten the repo's history to fix this.
