### ISSUE TITLE
NServiceBus CommonLogging 3.0.0 no longer strong-named signed?

### ISSUE THREAD

**Issue by tomlowi** [Particular/NServiceBus.CommonLogging#5]
Is there any particular reason why the new nuget package NServiceBus CommonLogging 3.0.0 for NServiceBus v6 no longer contains a strong-named signed assembly?
The previous version did, and all other NServiceBus packages for v6 still have strong-named assemblies.

Thx,
Iwan

**Comment by distantcam** [comment]
@tomlowi Sorry about that. It seems somewhere between v1 and v2 we broke signing.

We've released v4.0.0 which is now strong named. Hopefully that will resolve your issue.

**Comment by tomlowi** [comment]
Perfect, thanks!
